---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: "Stage: {{ _stage.name }} :: Check if kustomize directory is URL"
  ansible.builtin.set_fact:
    _kustomize_is_url: "{{ _stage.kustomize.directory.startswith(('http://', 'https://')) }}"
    _kustomize_dir_name: "{{ _stage.kustomize.directory | dirname | ansible.builtin.basename }}"

- name: "Stage: {{ _stage.name }} :: Ensure kustomize dir"
  when: not _kustomize_is_url
  ansible.builtin.file:
    path: >-
      {{
        [
          manifests_dir,
          _kustomize_dir_name
        ] | ansible.builtin.path_join
      }}
    state: directory
    mode: '0755'

- name: "Stage: {{ _stage.name }} :: Check if kustomize directory exists in synced work directory"
  when: not _kustomize_is_url and not _stage.kustomize.directory.startswith('/')
  ansible.builtin.stat:
    path: >-
      {{
        [_work_dir, _stage.kustomize.directory] |
        ansible.builtin.path_join
      }}
  register: _synced_kustomize_stat

- name: "Stage: {{ _stage.name }} :: Copy kustomize directory"
  when: not _kustomize_is_url
  ansible.builtin.copy:
    remote_src: "{{ _synced_kustomize_stat.stat.exists | default(false) }}"
    src: >-
      {{
        [_work_dir, _stage.kustomize.directory] | ansible.builtin.path_join
        if _synced_kustomize_stat.stat.exists | default(false)
        else _stage.kustomize.directory
      }}/
    dest: >-
      {{
        [
          manifests_dir,
          _kustomize_dir_name
        ] | ansible.builtin.path_join
      }}/

- name: "Stage: {{ _stage.name }} :: Set kustomize directory path"
  ansible.builtin.set_fact:
    _kustomize_apply_dir: >-
      {{
        _stage.kustomize.directory if _kustomize_is_url else
        [
          manifests_dir,
          _kustomize_dir_name
        ] | ansible.builtin.path_join
      }}

- name: "Stage: {{ _stage.name }} :: Apply Kustomize directory"
  hotloop_oc_apply_kustomize:
    directory: "{{ _kustomize_apply_dir }}"
    timeout: "{{ _stage.kustomize.timeout | default(60) }}"
  register: kustomize_result
