---
controller_ansible_host:
ansible_inventory: {}
base_dir: /home/zuul
bin_dir: "{{ base_dir }}/bin"
ssh_key_dir: "{{ base_dir }}/.ssh"
data_dir: "{{ base_dir }}/data"
cloud_config_dir: "{{ base_dir }}/.hotcloud"
controller_install_openstack_client: false
hotstack_cloud_secrets:
  auth_url: http://cloud.example.com:5000
  application_credential_id: app_credential_id
  application_credential_secret: app_credential_secret
  region_name: RegionOne
  interface: public
  identity_api_version: 3
  auth_type: v3applicationcredential
  # cacert: |
  #   -----BEGIN CERTIFICATE-----
  #   <certificate content here>
  #   -----END CERTIFICATE-----
