apiVersion: v1
data:
  server-ca-passphrase: MTIzNDU2Nzg=
kind: Secret
metadata:
  name: octavia-ca-passphrase
  namespace: openstack
type: Opaque
---
apiVersion: v1
data:
  AdminPassword: MTIzNDU2Nzg=
  AodhDatabasePassword: MTIzNDU2Nzg=
  AodhPassword: MTIzNDU2Nzg=
  BarbicanDatabasePassword: MTIzNDU2Nzg=
  BarbicanPassword: MTIzNDU2Nzg=
  BarbicanSimpleCryptoKEK: c0VGbWRGakRVcVJNMlZlbVlzbFY1eUdOV2pva2lvSlhzZzhOcmxjM2RyVT0=
  CeilometerPassword: MTIzNDU2Nzg=
  CinderDatabasePassword: MTIzNDU2Nzg=
  CinderPassword: MTIzNDU2Nzg=
  DatabasePassword: MTIzNDU2Nzg=
  DbRootPassword: MTIzNDU2Nzg=
  DesignateDatabasePassword: MTIzNDU2Nzg=
  DesignatePassword: MTIzNDU2Nzg=
  GlanceDatabasePassword: MTIzNDU2Nzg=
  GlancePassword: MTIzNDU2Nzg=
  HeatAuthEncryptionKey: NzY3YzNlZDA1NmNiYWEzYjlkZmVkYjhjNmY4MjViZjA=
  HeatDatabasePassword: MTIzNDU2Nzg=
  HeatPassword: MTIzNDU2Nzg=
  IronicDatabasePassword: MTIzNDU2Nzg=
  IronicInspectorDatabasePassword: MTIzNDU2Nzg=
  IronicInspectorPassword: MTIzNDU2Nzg=
  IronicPassword: MTIzNDU2Nzg=
  KeystoneDatabasePassword: MTIzNDU2Nzg=
  ManilaDatabasePassword: MTIzNDU2Nzg=
  ManilaPassword: MTIzNDU2Nzg=
  MetadataSecret: MTIzNDU2Nzg0Mg==
  NeutronDatabasePassword: MTIzNDU2Nzg=
  NeutronPassword: MTIzNDU2Nzg=
  NovaAPIDatabasePassword: MTIzNDU2Nzg=
  NovaCell0DatabasePassword: MTIzNDU2Nzg=
  NovaCell1DatabasePassword: MTIzNDU2Nzg=
  NovaPassword: MTIzNDU2Nzg=
  OctaviaDatabasePassword: MTIzNDU2Nzg=
  OctaviaHeartbeatKey: MTIzNDU2Nzg=
  OctaviaPassword: MTIzNDU2Nzg=
  PlacementDatabasePassword: MTIzNDU2Nzg=
  PlacementPassword: MTIzNDU2Nzg=
  SwiftPassword: MTIzNDU2Nzg=
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque