apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/nncm-config-type: standard
  name: master-0
  namespace: openstack
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server:
        - 192.168.32.254
    interfaces:
    - name: internalapi
      type: vlan
      description: internalapi vlan interface
      ipv4:
        address:
        - ip: 172.17.0.10
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      state: up
      vlan:
        base-iface: ens4
        id: "20"
    - name: storage
      type: vlan
      description: storage vlan interface
      ipv4:
        address:
        - ip: 172.18.0.10
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      state: up
      vlan:
        base-iface: ens4
        id: "21"
    - name: tenant
      type: vlan
      description: tenant vlan interface
      ipv4:
        address:
        - ip: 172.19.0.10
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      state: up
      vlan:
        base-iface: ens4
        id: "22"
    - description: ctlplane interface
      mtu: 1442
      name: ens4
      state: up
      type: ethernet
    - name: ospbr
      type: linux-bridge
      description: linux-bridge over ctlplane interface
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens4
          vlan: {}
      ipv4:
        address:
        - ip: 192.168.122.10
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      state: up
    - name: ironic
      type: linux-bridge
      description: Ironic bridge
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens5
      ipv4:
        address:
        - ip: 172.20.1.10
          prefix-length: "24"
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
    - name: ironicvrf
      description: Ironic VRF
      state: up
      type: vrf
      vrf:
        port:
        - ironic
        route-table-id: 10
    route-rules:
      config: []
    routes:
      config:
      - destination: 0.0.0.0/0
        metric: 150
        next-hop-address: 172.20.1.1
        next-hop-interface: ironic
        table-id: 10
      - destination: 172.20.1.0/24
        metric: 150
        next-hop-address: 192.168.122.1
        next-hop-interface: ospbr
  nodeSelector:
    kubernetes.io/hostname: master-0
    node-role.kubernetes.io/worker: ""
